# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='slug',
        ),
    ]
