# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
